name: Cabal CI

on:
  pull_request:
    branches:
      - master

jobs:
  cabal-build:
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            "ubuntu-20.04",
            "ubuntu-22.04",
            "macos-12",
            "macOS-13",
            "windows-2019",
            "windows-2022",
          ]
        ghc: ["9.4.8", "9.6.4", "9.8.1"]
        exe: ["youtube-mpv-native-host"]
    name: ${{ matrix.os }}/GHC ${{ matrix.ghc }}/${{ matrix.exe }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2.6.0
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: "3.10.2.0"

      - name: Freeze
        run: |
          cabal freeze

      - name: Cache ~/.cabal/store
        uses: actions/cache@v3.3.2
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Build
        run: |
          cabal build -O2 exe:${{matrix.exe}}

      - name: Find Artifact Path
        run: |
          echo "artifactPath=$(cabal list-bin exe:${{matrix.exe}})" >> ${{ runner.os == 'Windows' && '$env:' || '$' }}GITHUB_ENV

      - name: Upload build artifacts
        if: ${{matrix.ghc}} == "9.8.1" && (${{matrix.os}} == "ubuntu-22.04" || ${{matrix.os}} == "macOS-13" || ${{matrix.os}} == "windows-2022")
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.exe }}-${{ runner.os }}-${{matrix.ghc}}
          path: ${{ env.artifactPath }}
