name: Cabal CI

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        default: .
        type: string

jobs:
  cabal-build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "macOS-13", "windows-2022"]
        ghc: ["9.6.4", "9.8.1"]
        exe: ["youtube-mpv-native-host"]
    name: ${{ matrix.os }}/GHC ${{ matrix.ghc }}/${{ matrix.exe }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2.6.0
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: "3.10.2.0"

      - name: Freeze
        working-directory: ${{ inputs.working-directory }}
        run: |
          cabal freeze

      - name: Cache ~/.cabal/store
        uses: actions/cache@v3.3.2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            native/dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('native/cabal.project.freeze') }}

      - name: Build
        working-directory: ${{ inputs.working-directory }}
        run: |
          cabal build -O2 exe:${{matrix.exe}}

      - name: Find Artifact Path
        working-directory: ${{ inputs.working-directory }}
        run: |
          echo artifactPath=$(cabal list-bin -O2 exe:${{matrix.exe}}) >> ${{ runner.os == 'Windows' && '$env:' || '$' }}GITHUB_ENV

      - name: Upload build artifacts
        if: ${{matrix.ghc == '9.8.1' && (matrix.os == 'ubuntu-22.04' || matrix.os == 'macOS-13' || matrix.os == 'windows-2022')}}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.exe }}-${{ runner.os }}-${{matrix.ghc}}
          path: ${{ env.artifactPath }}
